version: '3.3'
services:
  challenge_node_red:
    container_name: challenge_node_red
    build: node-red
    volumes:
      - ./node-red/volume:/data
    ports:
      - "1880:1880"

  challenge_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  challenge_backend:
    container_name: challenge_backend
    build: backend_node
    volumes:
      - ./requirements/resources/events.json:/uploads/events.json
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: 'mongodb://root:rootpassword@challenge_mongodb:27017/admin'
      JWT_KEY: 'D5rN5Y2fBRG4ee4aRexr37nE5GeFEc9d'

  challenge_react:
    container_name: challenge_react
    build: front_react
    ports:
      - "3000:80"
